title: Naga
tagline: Thoughts and things on Front-end development and related topics, by Steve Barnett.
author: Steve Barnett
email: steve@naga.co.za
description: Thoughts and things on Front-end development and related topics, by Steve Barnett.
github_username: SteveBarnett
image: /img/me.jpg

permalink: pretty

# Build settings
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

collections:
  sounds-like-inputs:
    output: true
  sounds-like-groups-radios:
    output: true
  sounds-like-groups:
    output: true
  sounds-like-errors:
    output: true
  sounds-like-describedbys:
    output: true
  sounds-like-accessible-names:
    output: true

css-version: 1.2.5
