title: Naga
tagline: Thoughts and things on Front-end development and related topics, by Steve Barnett.
author: Steve Barnett
email: steve@naga.co.za
description: Thoughts and things on Front-end development and related topics, by Steve Barnett.
twitter_username: maxbarners
github_username:  SteveBarnett

permalink: pretty

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed
