title: Naga
tagline: Thoughts and things on Front-end development and related topics, by Steve Barnett.
author: Steve Barnett
email: steve@naga.co.za
description: Thoughts and things on Front-end development and related topics, by Steve Barnett.
github_username: SteveBarnett
image: /img/logo.png

permalink: /:year/:month/:day/:title/

# Build settings
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

collections:
  sounds-like-inputs:
    output: true
  sounds-like-groups-radios:
    output: true
  sounds-like-groups:
    output: true
  sounds-like-errors:
    output: true
  sounds-like-describedbys:
    output: true
  sounds-like-accessible-names:
    output: true
  more-accessible-products-sections:
    output: false
  more-accessible-products-ideas:
    output: true
    permalink: /more-accessible-products/:name
  more-accessible-products-actions:
    output: true

css-version: 1.5.1
